// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using socialBrothersCase.DatabaseContexts;

namespace socialBrothersCase.Database
{
    [DbContext(typeof(AdressesContext))]
    [Migration("20211030100953_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("socialBrothersCase.Models.Adress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseNumber")
                        .HasMaxLength(250)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f744af43-a61f-4fe8-b4ce-d50762e8c905"),
                            Country = "The Netherlands",
                            HouseNumber = 100,
                            Location = "Utrecht",
                            PostalCode = "3526 KS",
                            Street = "Europalaan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
